### ISSUE TITLE
ownCloud 7 Launch Task List

### ISSUE THREAD

**Issue by tomneedham** [owncloud/owncloud.org#24]
Tasks to be completed before the launch of the new website (along with ownCloud 7):

Content:
- [x] Home page text
- [x] Install page
- [x] Contribute page
- [x] Security page(advisories need porting, and php render code developed)
- [x] Contact page
- [x] Server Installation instructions on /install
- [x]  Add link to advisories page
- [x] Add sync client testing information
- [x] Update desktop client screenshot

Design:
- [x] Documentation design
- [x] Splash image adjustment
- [x] Providers page

Tweaks:
- [x] Fix images on history page
- [x] Fix images on features page
- [x] Move menus from Wordpress to php files (header)
- [x] Move menus from Wordpress to php files (footer)

@jancborchardt @karlitschek @MariekevC
